### ISSUE TITLE
make_response_from_XXX Content cannot be Chinese

### ISSUE THREAD

**Issue by aleimu** [pyexcel-webwares/Flask-Excel#35]
Support for Chinese is not very good, can you optimize it, give the encoding or decode similar parameters in the api interface to control

**Comment by aleimu** [comment]
`
@app.route("/download_file_named_in_unicode_csv", methods=['GET'])
def download_file_named_in_unicode():
    test_list = [['名字', '分数'], [1, 2], [3, 4], [5.0, 6.1], ["A", "B"], ['名字1', '分数2'], [1, 2], [3, 4], [5.0, 6.1],
             ["A", "B"]]
    return excel.make_response_from_array(test_list, "csv", file_name=u"中文文件名", encoding="ansi")
`
`
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/myself/test/flask_excel_quick_start.py", line 189, in download_file_named_in_unicode_xls
    return excel.make_response_from_array(test_list, "xls", file_name=u"xls涓枃鏂囦欢鍚?)
  File "D:\Python27\lib\site-packages\pyexcel_webio\__init__.py", line 370, in make_response_from_array
    file_stream = pe.save_as(array=array, dest_file_type=file_type, **keywords)
  File "D:\Python27\lib\site-packages\pyexcel\core.py", line 83, in save_as
    return sources.save_sheet(sheet, **dest_keywords)
  File "D:\Python27\lib\site-packages\pyexcel\internal\core.py", line 43, in save_sheet
    return _save_any(a_source, sheet)
  File "D:\Python27\lib\site-packages\pyexcel\internal\core.py", line 55, in _save_any
    a_source.write_data(instance)
  File "D:\Python27\lib\site-packages\pyexcel\plugins\sources\output_to_memory.py", line 38, in write_data
    self._content, sheet, **self._keywords
  File "D:\Python27\lib\site-packages\pyexcel\plugins\renderers\excel.py", line 35, in render_sheet_to_stream
    file_stream, sheet, file_type=self._file_type, **keywords
  File "D:\Python27\lib\site-packages\pyexcel\plugins\renderers\excel.py", line 28, in render_sheet_to_file
    save_data(file_name, data, **keywords)
  File "D:\Python27\lib\site-packages\pyexcel_io\io.py", line 127, in save_data
    **keywords
  File "D:\Python27\lib\site-packages\pyexcel_io\io.py", line 144, in store_data
    writer.write(data)
  File "D:\Python27\lib\site-packages\pyexcel_io\book.py", line 57, in __exit__
    self.close()
  File "D:\Python27\lib\site-packages\pyexcel_xls\xlsw.py", line 93, in close
    self.work_book.save(self._file_alike_object)
  File "D:\Python27\lib\site-packages\xlwt\Workbook.py", line 710, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "D:\Python27\lib\site-packages\xlwt\Workbook.py", line 674, in get_biff_data
    shared_str_table   = self.__sst_rec()
  File "D:\Python27\lib\site-packages\xlwt\Workbook.py", line 636, in __sst_rec
    return self.__sst.get_biff_record()
  File "D:\Python27\lib\site-packages\xlwt\BIFFRecords.py", line 77, in get_biff_record
    self._add_to_sst(s)
  File "D:\Python27\lib\site-packages\xlwt\BIFFRecords.py", line 92, in _add_to_sst
    u_str = upack2(s, self.encoding)
  File "D:\Python27\lib\site-packages\xlwt\UnicodeUtils.py", line 50, in upack2
    us = unicode(s, encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
127.0.0.1 - - [31/Oct/2018 18:38:05] "GET /download_file_named_in_unicode_xls HTTP/1.1" 500 -
`

**Comment by aleimu** [comment]
Solution:     test_list_utf8 = [[u'名字', u'分数'], [1, 2], [3, 4], [5.0, 6.1], [u"A", u"B"], [u'名字1', u'分数2'], [1, 2], [3, 4], [5.0, 6.1],[u"A", u"B"]]

**Comment by chfw** [comment]
Aha! you are using python 2.

Alternatively, you insert the following to the beginning of your file:

```
#coding=utf-8
from __future__ import unicode_literals
```

Or use python 3.

**Comment by aleimu** [comment]
Thanks

**Comment by tidetam** [comment]
I use python3.7  respond can be made, but chinese characters are still wrong in the excel file
I use **make_response_from_array**

**Comment by aleimu** [comment]
excel.make_response_from_array(result, "xlsx", file_name="中文_" + str_date)  
use xlsx !

**Comment by tidetam** [comment]
Thank you very much.
I found the problem is that the content in the csv is correct.  But open it
in excel, will be messy code.  Because of the BOM is not added in the csv
file and excel don't use utf-8 to decode.  So to solve this question, I
want to know how to add BOM to the result of the make_respon_from_xxx method

Best regards,
Tide


ARem <notifications@github.com> 于2018年11月21日周三 上午10:59写道：
