### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'get_array'

### ISSUE THREAD

**Issue by JasonCrowe** [pyexcel-webwares/Flask-Excel#50]
I have the following function that works perfectly on my local environment with flask 1.1.2 on python 3.8.

```
@app.route("/upload", methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        column_num = [x.lower() for x in request.get_array(field_name='file')[0]].index('address')
        rs = [P.upsert(process_address(Address(x[column_num])), ['address']) for x in request.get_array(field_name='file')[1:]]
        return '''
            <!doctype html>
            <title>File Uploaded</title>
            <h1>Excel File Uploaded</h1>
            <p><a href="./admin/property/"> View records... </a></p>'''
    return '''
    <!doctype html>
    <title>Upload an excel file</title>
    <h1>Excel file upload (csv, tsv, csvz, tsvz only)</h1>
    <form action="" method=post enctype=multipart/form-data><p>
    <input type=file name=file><input type=submit value=Upload>
    </form>
    '''
```

When I move it over to my pythonanywhere account I get the following error on flask 1.1.1 / python 3.8.
```

2020-07-29 02:57:16,407: Exception on /upload [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jcrowe/mysite/flask_app.py", line 143, in upload_file
    column_num = [x.lower() for x in request.get_array(field_name='file')[0]].index('address')
  File "/usr/lib/python3.8/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'get_array'

```
Can anyone help with this? I don't understand why the get_array function isn't there.

**Comment by JasonCrowe** [comment]
I found the issue.

I had:
app = Flask(__name__)
in the file twice. Once before and once after app was passed to pyexcel.
